### PR TITLE
Finished home nav

### PR DESCRIPTION
**Pull request by Tekipeps**

### CODE REVIEW

**Comment by Tekipeps** [comment]
@BidemiEnoch checkout this branch

**Comment by BidemiEnoch** [comment]
Wait...

**Comment by BidemiEnoch** [comment]
conflicting ideas...
1) use styled components vs dont use styled components, we literally agreed on node sass, you LITERALLY said we shouldnt use both
2) `const elem:React.FC vs FC,` it makes no difference to destructure FC.
3) `const elem=():JSX.element=>{} vs const elem=():ReactElement=>{}`
4) 
Screenshot (67)
by restructuring the folders, *my work* now literally shows *one contributor(you)* implying ive made 0 contributions to the files you have edited which i know should'nt mean anything but i dont like that. 
5) Ive made multiple changes here on my side that are similar to/or conflict what you've done `the method of organizing the routes->home, login e.t.c`
My final verdict...
this exact pr cant be merged, but the changes would go through ofc on a different pr(views/home shoudnt go to waste)
I'll clone this branch, merge it with mine(views/home and the file directory changes stay, same with styled-components) and the ui updates  ive made.
I will scrap sass completely since you apparently woudnt use sass. But before i make the pr, well decide on...
React.fc vs fc and jsx.element vs reactelement, non uniform conventions are annoying. Then after the pr(on which we must have decided on react.fc which i still find very annoying) I'll take a break so you can make your changes to /client while i inspect the models/schemas and stuffs(or just eat popcorn and watch you have all the fun for... 2 days?lol)
This pr isnt going through, please inform me before making changes these divergent to /client. Im the lead frontend engineer(wink) *Laughs in { FC } from 'react'*. Holla.
PS: if you merge this pr, ill refuse to comtribute anymore to this project and burn your room down with gasoline and liquor... seriously... hola

**Comment by Tekipeps** [comment]
okay sir xD

not merging lol

**Comment by BidemiEnoch** [comment]
Give me till saturday, I would make a pr with your changes and mine, then i take break and you continue your changes.
**highlights...**
- im scrapping node sass, styled components stays(yaaay, you win, dark theme is my next objective and ive weighed that toggling classes with node-sass is stressful)
- FC over React.FC, sorry(I know you want to blast my monitor with a cannon rn), Ive seen most repos use react.fc(which is why you see this as natural), but it makes absolutely no difference to destructure, most repos that use react.fc also use react.usestate() react.usehistory() react.useeffect(), they destructure nothing(for whatever f...in reason probs becos typing r-e-a-c-t everytime is fun. You like how your editor colors react.fc dont you? makes the react blue and fc orange and the colors turn you on lol.
- ReactElement over JSX.element( Because some components return pure objects(like props.children) and react cloned objects, jsx.element is too specific, reactelement covers pretty much every return type
- ~~im scrapping react and typescript, switching to jquery cos $ sexy asf and porting to a php server(bye node)~~

**Comment by Tekipeps** [comment]
You're really accurate on the React.FC angle xD
The third point is quite interesting tho.. will research that

~~also your'e free to switch to jquery and php.. node too stressful~~

**Comment by BidemiEnoch** [comment]
inaccurate about how destructuring type fc from react is literally not different from using react.fc? or the colors team? you couldve ended up with a teammate who would complain about you using useState instead of react.useState, apart from the fact every other fancy repo uses react.fc, why use it over fc?

**Comment by Tekipeps** [comment]
lets use FC then .. i'm just used to typing React.FC and it seems cool to me
I can do anyone anyways..

**Comment by BidemiEnoch** [comment]
aight I'll pr on or before saturday then... adios...
also... press an f for node_sass

**Comment by Tekipeps** [comment]
okay man..
lemme go do some ai stuff till sunday

closing pr in an hour

**Pull request closed without merging**
