### PR TITLE
My branch

### PR DESCRIPTION
**Pull request by BidemiEnoch**
Updated the overall UI, the login and team pages, e.t.c

### CODE REVIEW

**Review by Tekipeps — CHANGES_REQUESTED** [review]
add `yarn-error.log` to .gitignore

**Comment by BidemiEnoch** [comment]
> 
> 
> add `yarn-error.log` to .gitignore

yarn-error.log is missing in your gitignore too..., fine

**Comment by Tekipeps** [comment]
Yeah I didnt add it to gitignore and it wasn't in staging.., The error log file is unique to each person and should not be in version control @BidemiEnoch

**Review by Tekipeps — COMMENTED** [review]
cool

**Comment by Tekipeps** [comment]
Its still on version control tho but ill delete it myself

**Review by Tekipeps — APPROVED** [review]
Merging this

**Comment by BidemiEnoch** [comment]
> 
> 
> cool

done

**Pull request merged**
