### PR TITLE
Adding final touches to the frontend

### PR DESCRIPTION
**Pull request by BidemiEnoch**
Im done with the frontend, a.k.a im done with my contributions, you can make updates to the UI still if you want to, It was nice writing code with y'all, hola

### CODE REVIEW

**Comment by Tekipeps** [comment]
you're not done o
pull latest code and style that logout button for me
even profile page and page for single post is not complete lol

**Comment by Tekipeps** [comment]
you're not done o
pull latest code and style that logout button for me
even profile page and page for single post is not complete lol

**Comment by BidemiEnoch** [comment]
> 
> 
> you're not done o
> pull latest code and style that logout button for me
> even profile page and page for single post is not complete lol

Ive styled the button, I pulled your repo before making this PR

**Comment by BidemiEnoch** [comment]
yh... about the profile page... merge the PR and check it out, I updated it, Ill see if I can add stuff to the profile page later today

**Comment by BidemiEnoch** [comment]
Oh wait I haven't pulled #78...

**Pull request closed without merging**
